/* soapServer.c
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.16 2014-02-21 07:13:51 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ws_get_vmkey"))
		return soap_serve_ns1__ws_USCOREget_USCOREvmkey(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ws_get_hardware_info_by_serialnumber"))
		return soap_serve_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ws_get_all_physical_server"))
		return soap_serve_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ws_get_server_statictis"))
		return soap_serve_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:get_totalserver_per_product"))
		return soap_serve_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ws_update_servername_by_serialnumber"))
		return soap_serve_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREvmkey(struct soap *soap)
{	struct ns1__ws_USCOREget_USCOREvmkey soap_tmp_ns1__ws_USCOREget_USCOREvmkey;
	struct ns1__ws_USCOREget_USCOREvmkeyResponse soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse;
	char * soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse.return_ = &soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREvmkey(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkey);
	if (!soap_get_ns1__ws_USCOREget_USCOREvmkey(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkey, "ns1:ws_get_vmkey", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__ws_USCOREget_USCOREvmkey(soap, soap_tmp_ns1__ws_USCOREget_USCOREvmkey.list, soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse, "ns1:ws_get_vmkeyResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse, "ns1:ws_get_vmkeyResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap *soap)
{	struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber;
	struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse;
	char * soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse.return_ = &soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber);
	if (!soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber, "ns1:ws_get_hardware_info_by_serialnumber", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber.serial_USCOREnumber, soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse, "ns1:ws_get_hardware_info_by_serialnumberResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse, "ns1:ws_get_hardware_info_by_serialnumberResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap *soap)
{	struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver;
	struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse;
	char * soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse.return_ = &soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver);
	if (!soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver, "ns1:ws_get_all_physical_server", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse, "ns1:ws_get_all_physical_serverResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse, "ns1:ws_get_all_physical_serverResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap *soap)
{	struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis;
	struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse;
	char * soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse.return_ = &soap_tmp_string;
	soap_default_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis);
	if (!soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis, "ns1:ws_get_server_statictis", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse, "ns1:ws_get_server_statictisResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse, "ns1:ws_get_server_statictisResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap *soap)
{	struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct;
	struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse;
	char * soap_tmp_string;
	soap_default_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse.return_ = &soap_tmp_string;
	soap_default_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct);
	if (!soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct, "ns1:get_totalserver_per_product", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse, "ns1:get_totalserver_per_productResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse, "ns1:get_totalserver_per_productResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap *soap)
{	struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber;
	struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse;
	char * soap_tmp_string;
	soap_default_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse.return_ = &soap_tmp_string;
	soap_default_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber);
	if (!soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber, "ns1:ws_update_servername_by_serialnumber", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber.serial_USCOREnumber, soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber.servername, soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse.return_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse, "ns1:ws_update_servername_by_serialnumberResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse, "ns1:ws_update_servername_by_serialnumberResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
