/* soapH.h
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber
#define SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, const char*, int, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber * SOAP_FMAC4 soap_in_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, const char*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber
#define soap_write_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, data),0) || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, data, "ns1:ws_update_servername_by_serialnumber", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber * SOAP_FMAC4 soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber
#define soap_read_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse
#define SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, const char*, int, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse * SOAP_FMAC4 soap_in_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, const char*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, const struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse
#define soap_write_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, data),0) || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, data, "ns1:ws_update_servername_by_serialnumberResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse * SOAP_FMAC4 soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(struct soap*, struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse
#define soap_read_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct
#define SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, const char*, int, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *, const char*);
SOAP_FMAC3 struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct * SOAP_FMAC4 soap_in_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, const char*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *, const char*, const char*);

#ifndef soap_write_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct
#define soap_write_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, data),0) || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, data, "ns1:get_totalserver_per_product", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct * SOAP_FMAC4 soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct *, const char*, const char*);

#ifndef soap_read_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct
#define soap_read_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse
#define SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, const char*, int, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *, const char*);
SOAP_FMAC3 struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse * SOAP_FMAC4 soap_in_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, const char*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, const struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *, const char*, const char*);

#ifndef soap_write_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse
#define soap_write_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, data),0) || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, data, "ns1:get_totalserver_per_productResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse * SOAP_FMAC4 soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(struct soap*, struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *, const char*, const char*);

#ifndef soap_read_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse
#define soap_read_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictis
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictis (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREserver_USCOREstatictis
#define soap_write_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, data, "ns1:ws_get_server_statictis", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREserver_USCOREstatictis
#define soap_read_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse
#define soap_write_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, data, "ns1:ws_get_server_statictisResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(struct soap*, struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse
#define soap_read_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver
#define soap_write_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, data, "ns1:ws_get_all_physical_server", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver
#define soap_read_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse
#define soap_write_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, data, "ns1:ws_get_all_physical_serverResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(struct soap*, struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse
#define soap_read_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber
#define soap_write_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, data, "ns1:ws_get_hardware_info_by_serialnumber", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber
#define soap_read_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse
#define soap_write_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, data, "ns1:ws_get_hardware_info_by_serialnumberResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(struct soap*, struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse
#define soap_read_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkey
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkey (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREvmkey(struct soap*, struct ns1__ws_USCOREget_USCOREvmkey *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREvmkey(struct soap*, const struct ns1__ws_USCOREget_USCOREvmkey *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREvmkey(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREvmkey *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREvmkey * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREvmkey(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREvmkey *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREvmkey(struct soap*, const struct ns1__ws_USCOREget_USCOREvmkey *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREvmkey
#define soap_write_ns1__ws_USCOREget_USCOREvmkey(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREvmkey(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREvmkey(soap, data, "ns1:ws_get_vmkey", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREvmkey * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREvmkey(struct soap*, struct ns1__ws_USCOREget_USCOREvmkey *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREvmkey
#define soap_read_ns1__ws_USCOREget_USCOREvmkey(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREvmkey(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkeyResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkeyResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, struct ns1__ws_USCOREget_USCOREvmkeyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREvmkeyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, const char*, int, const struct ns1__ws_USCOREget_USCOREvmkeyResponse *, const char*);
SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREvmkeyResponse * SOAP_FMAC4 soap_in_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, const char*, struct ns1__ws_USCOREget_USCOREvmkeyResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, const struct ns1__ws_USCOREget_USCOREvmkeyResponse *, const char*, const char*);

#ifndef soap_write_ns1__ws_USCOREget_USCOREvmkeyResponse
#define soap_write_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, data),0) || soap_put_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, data, "ns1:ws_get_vmkeyResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns1__ws_USCOREget_USCOREvmkeyResponse * SOAP_FMAC4 soap_get_ns1__ws_USCOREget_USCOREvmkeyResponse(struct soap*, struct ns1__ws_USCOREget_USCOREvmkeyResponse *, const char*, const char*);

#ifndef soap_read_ns1__ws_USCOREget_USCOREvmkeyResponse
#define soap_read_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostring(soap, data),0) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
