/* soapClient.c
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.16 2014-02-21 07:13:51 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREvmkey(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *list, char **return_)
{	struct ns1__ws_USCOREget_USCOREvmkey soap_tmp_ns1__ws_USCOREget_USCOREvmkey;
	struct ns1__ws_USCOREget_USCOREvmkeyResponse *soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#ws_get_vmkey";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ws_USCOREget_USCOREvmkey.list = list;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREvmkey(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkey);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREvmkey(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkey, "ns1:ws_get_vmkey", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREvmkey(soap, &soap_tmp_ns1__ws_USCOREget_USCOREvmkey, "ns1:ws_get_vmkey", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse = soap_get_ns1__ws_USCOREget_USCOREvmkeyResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse->return_)
		*return_ = *soap_tmp_ns1__ws_USCOREget_USCOREvmkeyResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *serial_USCOREnumber, char **return_)
{	struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber;
	struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse *soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#ws_get_hardware_info_by_serialnumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber.serial_USCOREnumber = serial_USCOREnumber;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber, "ns1:ws_get_hardware_info_by_serialnumber", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber, "ns1:ws_get_hardware_info_by_serialnumber", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse = soap_get_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse->return_)
		*return_ = *soap_tmp_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_)
{	struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver;
	struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse *soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#ws_get_all_physical_server";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver, "ns1:ws_get_all_physical_server", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(soap, &soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver, "ns1:ws_get_all_physical_server", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse = soap_get_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse->return_)
		*return_ = *soap_tmp_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_)
{	struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis;
	struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse *soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#ws_get_server_statictis";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis, "ns1:ws_get_server_statictis", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(soap, &soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictis, "ns1:ws_get_server_statictis", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse = soap_get_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse->return_)
		*return_ = *soap_tmp_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_)
{	struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct;
	struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse *soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#get_totalserver_per_product";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct, "ns1:get_totalserver_per_product", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(soap, &soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct, "ns1:get_totalserver_per_product", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse = soap_get_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse->return_)
		*return_ = *soap_tmp_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *serial_USCOREnumber, char *servername, char **return_)
{	struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber;
	struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse *soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://icloud.vng.com.vn/services/sdk/index";
	if (soap_action == NULL)
		soap_action = "https://icloud.vng.com.vn/services/sdk/index#ws_update_servername_by_serialnumber";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber.serial_USCOREnumber = serial_USCOREnumber;
	soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber.servername = servername;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber, "ns1:ws_update_servername_by_serialnumber", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(soap, &soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber, "ns1:ws_update_servername_by_serialnumber", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse = soap_get_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse->return_)
		*return_ = *soap_tmp_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse->return_;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
