/* soapStub.h
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"https://icloud.vng.com.vn/services/sdk/index"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20816
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkeyResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkeyResponse (9)
/* ns1:ws_get_vmkeyResponse */
struct ns1__ws_USCOREget_USCOREvmkeyResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkey
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREvmkey (10)
/* ns1:ws_get_vmkey */
struct ns1__ws_USCOREget_USCOREvmkey
{
	char *list;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse (12)
/* ns1:ws_get_hardware_info_by_serialnumberResponse */
struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumberResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber (13)
/* ns1:ws_get_hardware_info_by_serialnumber */
struct ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber
{
	char *serial_USCOREnumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse (15)
/* ns1:ws_get_all_physical_serverResponse */
struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserverResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver (16)
/* ns1:ws_get_all_physical_server */
struct ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse (18)
/* ns1:ws_get_server_statictisResponse */
struct ns1__ws_USCOREget_USCOREserver_USCOREstatictisResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictis
#define SOAP_TYPE_ns1__ws_USCOREget_USCOREserver_USCOREstatictis (19)
/* ns1:ws_get_server_statictis */
struct ns1__ws_USCOREget_USCOREserver_USCOREstatictis
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse
#define SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse (21)
/* ns1:get_totalserver_per_productResponse */
struct ns1__get_USCOREtotalserver_USCOREper_USCOREproductResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct
#define SOAP_TYPE_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct (22)
/* ns1:get_totalserver_per_product */
struct ns1__get_USCOREtotalserver_USCOREper_USCOREproduct
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse
#define SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse (24)
/* ns1:ws_update_servername_by_serialnumberResponse */
struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumberResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber
#define SOAP_TYPE_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber (25)
/* ns1:ws_update_servername_by_serialnumber */
struct ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber
{
	char *serial_USCOREnumber;	/* optional element of type xsd:string */
	char *servername;	/* optional element of type xsd:anyType */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (26)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (27)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (29)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (32)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (33)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns1__ws_USCOREget_USCOREvmkey(struct soap*, char *list, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*, char *serial_USCOREnumber, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*, char *serial_USCOREnumber, char *servername, char **return_);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREvmkey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREvmkey(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *list, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREhardware_USCOREinfo_USCOREby_USCOREserialnumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *serial_USCOREnumber, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREall_USCOREphysical_USCOREserver(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREget_USCOREserver_USCOREstatictis(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREtotalserver_USCOREper_USCOREproduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__ws_USCOREupdate_USCOREservername_USCOREby_USCOREserialnumber(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *serial_USCOREnumber, char *servername, char **return_);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
