/* soapClient.c
   Generated by gSOAP 2.8.16 from rcx.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.16 2014-02-28 06:41:33 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__newProduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *infoProduct, char **return_)
{	struct ns2__newProduct soap_tmp_ns2__newProduct;
	struct ns2__newProductResponse *soap_tmp_ns2__newProductResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://dcim.vng.com.vn:443/SDKTest/server.php";
	if (soap_action == NULL)
		soap_action = "https://dcim.vng.com.vn/SDKTest/server.php/newProduct";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__newProduct.infoProduct = infoProduct;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns2__newProduct(soap, &soap_tmp_ns2__newProduct);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__newProduct(soap, &soap_tmp_ns2__newProduct, "ns2:newProduct", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__newProduct(soap, &soap_tmp_ns2__newProduct, "ns2:newProduct", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns2__newProductResponse = soap_get_ns2__newProductResponse(soap, NULL, "", "");
	if (!soap_tmp_ns2__newProductResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns2__newProductResponse->return_)
		*return_ = *soap_tmp_ns2__newProductResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__updateProduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *infoProduct, char **return_)
{	struct ns2__updateProduct soap_tmp_ns2__updateProduct;
	struct ns2__updateProductResponse *soap_tmp_ns2__updateProductResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://dcim.vng.com.vn:443/SDKTest/server.php";
	if (soap_action == NULL)
		soap_action = "https://dcim.vng.com.vn/SDKTest/server.php/updateProduct";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__updateProduct.infoProduct = infoProduct;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns2__updateProduct(soap, &soap_tmp_ns2__updateProduct);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__updateProduct(soap, &soap_tmp_ns2__updateProduct, "ns2:updateProduct", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__updateProduct(soap, &soap_tmp_ns2__updateProduct, "ns2:updateProduct", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns2__updateProductResponse = soap_get_ns2__updateProductResponse(soap, NULL, "", "");
	if (!soap_tmp_ns2__updateProductResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns2__updateProductResponse->return_)
		*return_ = *soap_tmp_ns2__updateProductResponse->return_;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__removeProduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ProductCode, char **return_)
{	struct ns2__removeProduct soap_tmp_ns2__removeProduct;
	struct ns2__removeProductResponse *soap_tmp_ns2__removeProductResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://dcim.vng.com.vn:443/SDKTest/server.php";
	if (soap_action == NULL)
		soap_action = "https://dcim.vng.com.vn/SDKTest/server.php/removeProduct";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns2__removeProduct.ProductCode = ProductCode;
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap_serializeheader(soap);
	soap_serialize_ns2__removeProduct(soap, &soap_tmp_ns2__removeProduct);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__removeProduct(soap, &soap_tmp_ns2__removeProduct, "ns2:removeProduct", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__removeProduct(soap, &soap_tmp_ns2__removeProduct, "ns2:removeProduct", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!return_)
		return soap_closesock(soap);
	*return_ = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns2__removeProductResponse = soap_get_ns2__removeProductResponse(soap, NULL, "", "");
	if (!soap_tmp_ns2__removeProductResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (return_ && soap_tmp_ns2__removeProductResponse->return_)
		*return_ = *soap_tmp_ns2__removeProductResponse->return_;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
